// ──────────────────────────────────────────────────────────────
// Module: Azure Communication Services — Email + SMS
// ──────────────────────────────────────────────────────────────
// Creates a single ACS resource with an Email Service and an
// Azure-managed email domain. SMS capabilities are enabled on
// the ACS resource; phone numbers are provisioned via the
// Azure portal (not Bicep) for the MVP.
//
// ACS is a **global** resource — `location` is always 'global'.
// Data residency is controlled via the `dataLocation` property.
// ──────────────────────────────────────────────────────────────
targetScope = 'resourceGroup'

// ── Parameters ────────────────────────────────────────────────

@description('The ACS resource name generated by the shared naming module.')
param resourceName string

@description('Tags to apply to all resources created by this module.')
param tags object

@description('Data residency location for ACS. Must be a valid ACS data location (e.g. "United States", "Europe", "Asia Pacific", "Australia").')
param dataLocation string = 'United States'

@description('Principal ID (object ID) of the API App Service managed identity to grant ACS Email Send access. Leave empty to skip the role assignment.')
param apiPrincipalId string = ''

@description('Principal ID of the API staging deployment-slot managed identity (S1 only). Leave empty to skip the role assignment.')
param stagingSlotPrincipalId string = ''

// ── Variables ─────────────────────────────────────────────────

// Email service name follows the ACS resource name with an '-email' suffix.
var emailServiceName = '${resourceName}-email'

// Contributor — AcsEmailNotificationService authenticates to ACS with the API's
// managed identity (DefaultAzureCredential). ACS exposes no granular data-plane
// "email sender" role as of writing; Contributor scoped to the ACS resource is
// the documented minimum for EmailClient.SendAsync under Entra ID auth. Re-check
// the ACS "authenticate with managed identity" docs for a narrower role before
// widening this pattern.
// https://learn.microsoft.com/azure/role-based-access-control/built-in-roles/general#contributor
var contributorRoleId = 'b24988ac-6180-42a0-ab88-20f7382dd24c'

// ── Azure Communication Services Account ──────────────────────
// 2025-05-01 does not exist; 2025-09-01 fails domain validation at deploy time.
#disable-next-line use-recent-api-versions
resource acsAccount 'Microsoft.Communication/communicationServices@2023-04-01' = {
  name: resourceName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: dataLocation
    linkedDomains: [
      azureManagedDomain.id
    ]
  }
}

// ── ACS Email Service ─────────────────────────────────────────
// See note on acsAccount above.
#disable-next-line use-recent-api-versions
resource emailService 'Microsoft.Communication/emailServices@2023-04-01' = {
  name: emailServiceName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: dataLocation
  }
}

// ── Azure-Managed Email Domain ────────────────────────────────
// Uses the built-in Azure-managed domain (AzureManagedDomain)
// for staging. Production should use a custom verified domain
// (e.g. notifications.rvserviceflow.com) configured separately.

#disable-next-line use-recent-api-versions
resource azureManagedDomain 'Microsoft.Communication/emailServices/domains@2023-04-01' = {
  parent: emailService
  name: 'AzureManagedDomain'
  location: 'global'
  tags: tags
  properties: {
    domainManagement: 'AzureManaged'
    userEngagementTracking: 'Disabled'
  }
}

// ── Role Assignments ─────────────────────────────────────────
// Grant the API managed identity (and the staging-slot identity on S1) the
// rights to call ACS Email Send via managed identity. Scoped to the ACS
// account only. Guarded by !empty(...) so the module still deploys when no
// App Service is present.

resource apiAcsContributorRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(apiPrincipalId)) {
  name: guid(acsAccount.id, apiPrincipalId, contributorRoleId)
  scope: acsAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalId: apiPrincipalId
    principalType: 'ServicePrincipal'
  }
}

resource stagingSlotAcsContributorRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(stagingSlotPrincipalId)) {
  name: guid(acsAccount.id, stagingSlotPrincipalId, contributorRoleId)
  scope: acsAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalId: stagingSlotPrincipalId
    principalType: 'ServicePrincipal'
  }
}

// ── Outputs ───────────────────────────────────────────────────

@description('The resource ID of the ACS account.')
output resourceId string = acsAccount.id

@description('The name of the ACS account.')
output name string = acsAccount.name

@description('The hostname of the ACS resource (e.g. acs-rvs-notify-staging-wus3-s01-001.communication.azure.com).')
output hostname string = acsAccount.properties.hostName

@description('The full endpoint URL of the ACS resource.')
output endpoint string = 'https://${acsAccount.properties.hostName}'

@description('The name of the Email Service resource.')
output emailServiceName string = emailService.name

@description('The Azure-managed MailFrom address (e.g. DoNotReply@<guid>.azurecomm.net).')
output azureManagedMailFrom string = azureManagedDomain.properties.mailFromSenderDomain

@description('The data residency location.')
output dataLocation string = dataLocation
