// ──────────────────────────────────────────────────────────────
// Module: Azure Communication Services — Email + SMS
// ──────────────────────────────────────────────────────────────
// Creates a single ACS resource with an Email Service and an
// Azure-managed email domain. SMS capabilities are enabled on
// the ACS resource; phone numbers are provisioned via the
// Azure portal (not Bicep) for the MVP.
//
// When `customDomainName` is set (staging — mail.staging.rvintake.com;
// prod — mail.rvintake.com; issue #532) a second, CustomerManaged domain is provisioned
// alongside the Azure-managed one and linked to the account. The
// Azure-managed *.azurecomm.net domain caps at 10 emails/hour with
// no support path to raise it; a verified custom sending subdomain
// is the only route to pilot volume and to a warmed sender
// reputation. Bicep provisions the domain and emits the SPF / DKIM
// / domain-ownership records it needs (`customDomainVerificationRecords`);
// `initiate-verification` and the quota-increase request stay manual
// (README "Deploy Production" step 4).
//
// ACS is a **global** resource — `location` is always 'global'.
// Data residency is controlled via the `dataLocation` property.
// ──────────────────────────────────────────────────────────────
targetScope = 'resourceGroup'

// ── Parameters ────────────────────────────────────────────────

@description('The ACS resource name generated by the shared naming module.')
param resourceName string

@description('Tags to apply to all resources created by this module.')
param tags object

@description('Data residency location for ACS. Must be a valid ACS data location (e.g. "United States", "Europe", "Asia Pacific", "Australia").')
param dataLocation string = 'United States'

@description('Principal ID (object ID) of the API App Service managed identity to grant ACS Email Send access. Leave empty to skip the role assignment.')
param apiPrincipalId string = ''

@description('Principal ID of the API staging deployment-slot managed identity (S1 only). Leave empty to skip the role assignment.')
param stagingSlotPrincipalId string = ''

@description('Custom sending subdomain to provision as a CustomerManaged domain (e.g. mail.rvintake.com). Empty = Azure-managed domain only. (#532)')
param customDomainName string = ''

// ── Variables ─────────────────────────────────────────────────

// Email service name follows the ACS resource name with an '-email' suffix.
var emailServiceName = '${resourceName}-email'

// Contributor — AcsEmailNotificationService authenticates to ACS with the API's
// managed identity (DefaultAzureCredential). ACS exposes no granular data-plane
// "email sender" role as of writing; Contributor scoped to the ACS resource is
// the documented minimum for EmailClient.SendAsync under Entra ID auth. Re-check
// the ACS "authenticate with managed identity" docs for a narrower role before
// widening this pattern.
// https://learn.microsoft.com/azure/role-based-access-control/built-in-roles/general#contributor
var contributorRoleId = 'b24988ac-6180-42a0-ab88-20f7382dd24c'

// ── Azure Communication Services Account ──────────────────────
// 2025-05-01 does not exist; 2025-09-01 fails domain validation at deploy time.
#disable-next-line use-recent-api-versions
resource acsAccount 'Microsoft.Communication/communicationServices@2023-04-01' = {
  name: resourceName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: dataLocation
    // Both domains are linked when a custom one is configured — the account can
    // send From either, and the managed domain stays available as a fallback.
    linkedDomains: empty(customDomainName)
      ? [ azureManagedDomain.id ]
      #disable-next-line BCP318
      : [ azureManagedDomain.id, customDomain.id ]
  }
}

// ── ACS Email Service ─────────────────────────────────────────
// See note on acsAccount above.
#disable-next-line use-recent-api-versions
resource emailService 'Microsoft.Communication/emailServices@2023-04-01' = {
  name: emailServiceName
  location: 'global'
  tags: tags
  properties: {
    dataLocation: dataLocation
  }
}

// ── Azure-Managed Email Domain ────────────────────────────────
// The built-in Azure-managed domain (<guid>.azurecomm.net). Always
// created — a From-address fallback wherever a custom domain is linked
// (staging, prod), and the only domain in an env without one. Microsoft caps it at 5 emails/min, 10/hour with
// no support path to raise it (#521).

#disable-next-line use-recent-api-versions
resource azureManagedDomain 'Microsoft.Communication/emailServices/domains@2023-04-01' = {
  parent: emailService
  name: 'AzureManagedDomain'
  location: 'global'
  tags: tags
  properties: {
    domainManagement: 'AzureManaged'
    userEngagementTracking: 'Disabled'
  }
}

// ── Custom (CustomerManaged) Sending Domain — #532 ────────────
// Provisioned as mail.rvintake.com in prod and mail.staging.rvintake.com
// in staging, each on its own ACS resource. On creation ACS returns
// `verificationRecords` (Domain + SPF as TXT, DKIM + DKIM2 as CNAME) —
// deterministic from the domain name and region, available before
// verification is initiated. main.bicep writes them into the Intake
// DNS zone. `verificationStates` stays NotStarted until an operator
// runs `az communication email domain initiate-verification`; sends
// From this domain fail until every record shows Verified.

#disable-next-line use-recent-api-versions
resource customDomain 'Microsoft.Communication/emailServices/domains@2023-04-01' = if (!empty(customDomainName)) {
  parent: emailService
  name: customDomainName
  location: 'global'
  tags: tags
  properties: {
    domainManagement: 'CustomerManaged'
    userEngagementTracking: 'Disabled'
  }
}

// ── Role Assignments ─────────────────────────────────────────
// Grant the API managed identity (and the staging-slot identity on S1) the
// rights to call ACS Email Send via managed identity. Scoped to the ACS
// account only. Guarded by !empty(...) so the module still deploys when no
// App Service is present.

resource apiAcsContributorRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(apiPrincipalId)) {
  name: guid(acsAccount.id, apiPrincipalId, contributorRoleId)
  scope: acsAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalId: apiPrincipalId
    principalType: 'ServicePrincipal'
  }
}

resource stagingSlotAcsContributorRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(stagingSlotPrincipalId)) {
  name: guid(acsAccount.id, stagingSlotPrincipalId, contributorRoleId)
  scope: acsAccount
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', contributorRoleId)
    principalId: stagingSlotPrincipalId
    principalType: 'ServicePrincipal'
  }
}

// ── Outputs ───────────────────────────────────────────────────

@description('The resource ID of the ACS account.')
output resourceId string = acsAccount.id

@description('The name of the ACS account.')
output name string = acsAccount.name

@description('The hostname of the ACS resource (e.g. acs-rvs-notify-staging-wus3-s01-001.communication.azure.com).')
output hostname string = acsAccount.properties.hostName

@description('The full endpoint URL of the ACS resource.')
output endpoint string = 'https://${acsAccount.properties.hostName}'

@description('The name of the Email Service resource.')
output emailServiceName string = emailService.name

@description('The Azure-managed MailFrom address (e.g. DoNotReply@<guid>.azurecomm.net).')
output azureManagedMailFrom string = azureManagedDomain.properties.mailFromSenderDomain

@description('True when a CustomerManaged sending domain was provisioned (#532).')
output hasCustomDomain bool = !empty(customDomainName)

@description('The custom MailFrom sender domain (e.g. mail.rvintake.com). Empty when no custom domain — use for the packet-email From address in prod.')
#disable-next-line BCP318
output customFromSenderDomain string = empty(customDomainName) ? '' : customDomain.properties.fromSenderDomain

@description('CNAME records the custom domain needs (DKIM, DKIM2), shaped for dns.bicep as [{ name, target }]. Empty when no custom domain.')
output customDomainCnameRecords array = empty(customDomainName) ? [] : [
  #disable-next-line BCP318
  { name: customDomain.properties.verificationRecords.DKIM.name, target: customDomain.properties.verificationRecords.DKIM.value }
  #disable-next-line BCP318
  { name: customDomain.properties.verificationRecords.DKIM2.name, target: customDomain.properties.verificationRecords.DKIM2.value }
]

@description('TXT record-set the custom domain needs, shaped for dns.bicep as [{ name, values }] where each value is a separate TXT record: the domain-ownership string and the SPF string (ending in -all). ACS puts both at the subdomain host, so they share one record-set name. DMARC is authored by the caller. Empty when no custom domain.')
output customDomainTxtRecords array = empty(customDomainName) ? [] : [
  {
    #disable-next-line BCP318
    name: customDomain.properties.verificationRecords.Domain.name
    values: [
      #disable-next-line BCP318
      customDomain.properties.verificationRecords.Domain.value
      #disable-next-line BCP318
      customDomain.properties.verificationRecords.SPF.value
    ]
  }
]

@description('Raw ACS verification records for the custom domain — for diffing against the zone with `az communication email domain show`. Empty object when no custom domain.')
#disable-next-line BCP318
output customDomainVerificationRecords object = empty(customDomainName) ? {} : customDomain.properties.verificationRecords

@description('The data residency location.')
output dataLocation string = dataLocation
