// ──────────────────────────────────────────────────────────────
// Module: Azure OpenAI – Whisper Speech-to-Text deployment
// ──────────────────────────────────────────────────────────────
// Whisper 001 Standard is only available in select regions
// (northcentralus, eastus2, swedencentral, etc.) so this module
// deploys a dedicated Azure OpenAI account in a supported region.
// ──────────────────────────────────────────────────────────────
targetScope = 'resourceGroup'

// ── Parameters ────────────────────────────────────────────────

@description('The Azure region for the Whisper OpenAI resource. Must support Whisper 001 Standard.')
param location string

@description('The environment name used for resource naming and network policy.')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environmentName string

@description('The Azure OpenAI resource name generated by the shared naming module.')
param resourceName string

@description('Tags to apply to all resources created by this module.')
param tags object

@description('Whisper deployment capacity in thousands of tokens per minute (K TPM). 1 = 1 000 TPM.')
@minValue(1)
param whisperCapacity int = 1

// ── Variables ─────────────────────────────────────────────────

var whisperDeploymentName = 'whisper'
var isProduction = environmentName != 'dev'

// ── Azure OpenAI Account (Whisper region) ─────────────────────

resource whisperAccount 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: resourceName
  location: location
  kind: 'OpenAI'
  sku: {
    name: 'S0'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    customSubDomainName: resourceName
    publicNetworkAccess: isProduction ? 'Disabled' : 'Enabled'
    networkAcls: {
      defaultAction: isProduction ? 'Deny' : 'Allow'
    }
  }
  tags: tags
}

// ── Whisper Speech-to-Text Model Deployment ───────────────────

resource whisperDeployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
  parent: whisperAccount
  name: whisperDeploymentName
  sku: {
    name: 'Standard'
    capacity: whisperCapacity
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: 'whisper'
      version: '001'
    }
    versionUpgradeOption: 'OnceCurrentVersionExpired'
  }
}

// ── Outputs ───────────────────────────────────────────────────

@description('The endpoint URL of the Whisper Azure OpenAI resource.')
output endpoint string = whisperAccount.properties.endpoint

@description('The resource name of the Whisper Azure OpenAI account.')
output name string = whisperAccount.name

@description('The name of the Whisper model deployment.')
output whisperDeploymentName string = whisperDeployment.name

@description('The principal ID of the system-assigned managed identity.')
output principalId string = whisperAccount.identity.principalId
